Add additional PHP settings and cookie configurations
MISP/misp-docker pull request #164
Opened 2024-10-04 14:16 UTC by Diogo-Rego

2024-10-04 14:28 UTC, Diogo-Rego commented
@ostefano  confirm cookie configuration in PHP

2024-10-04 14:38 UTC, ostefano requested changes
Can you prefix the PHP vars with PHP_SESSION and add some more documentation for each option?

2024-10-04 14:41 UTC, Diogo-Rego commented
> Can you prefix the PHP vars with PHP_SESSION and add some more documentation for each option?

@ostefano in *README.md* or *template.env*

2024-10-04 14:41 UTC, ostefano commented
> > Can you prefix the PHP vars with PHP_SESSION and add some more documentation for each option?
> 
> @ostefano in _README.md_ or _template.env_

Inside `template.env`

2024-10-04 14:53 UTC, Diogo-Rego commented
@ostefano 
```dotenv
# PHP FPM Configuration

## Basic PHP Settings
# Sets the maximum amount of memory a PHP script can consume.
# PHP_MEMORY_LIMIT=2048M
# Specifies the maximum time in seconds a PHP script can take to execute before being terminated.
# PHP_MAX_EXECUTION_TIME=300
# Defines the maximum size allowed for file uploads in a PHP script.
# PHP_UPLOAD_MAX_FILESIZE=50M
# Specifies the maximum size allowed for POST data that can be sent to PHP.
# PHP_POST_MAX_SIZE=50M
# Defines the maximum time in seconds that PHP should spend parsing input data, such as $_GET, $_POST, and $_COOKIE.
# PHP_MAX_INPUT_TIME=300

## Additional PHP Settings
# Sets the timeout (in minutes) of inactivity after which the user session expires.
# PHP_TIMEOUT=60
# Specifies the time (in minutes) that a session cookie should remain valid in the client's browser.
# PHP_COOKIE_TIMEOUT=10080
# Sets the default PHP configurations, which can be adjusted according to the application’s needs.
# PHP_DEFAULTS=php
# When enabled, this parameter forces the automatic regeneration of the session ID on each request.
# PHP_AUTO_REGENERATE=false
# When enabled, it checks the user agent on each request to help prevent session hijacking attacks.
# PHP_CHECK_AGENT=false
# When set to true, session cookies will only be sent over secure (HTTPS) connections.
# PHP_COOKIE_SECURE=true
# Defines the domain where the session cookie is valid. It should be left empty if you want the cookie to be valid only on the current domain.
# PHP_COOKIE_DOMAIN=
# Defines the SameSite policy for cookies, which controls how cookies are sent with requests from other sites. The "Lax" value allows cookies to be sent with top-level navigation requests and in the case of GET requests.
# PHP_COOKIE_SAMESITE=Lax
```

**OR**

```dotenv
# PHP FPM Configuration

## Basic PHP Settings
# Maximum memory a PHP script can use.
# PHP_MEMORY_LIMIT=2048M
# Maximum execution time for a PHP script in seconds.
# PHP_MAX_EXECUTION_TIME=300
# Maximum file upload size for PHP scripts.
# PHP_UPLOAD_MAX_FILESIZE=50M
# Maximum size for POST data sent to PHP.
# PHP_POST_MAX_SIZE=50M
# Maximum time PHP spends parsing input data in seconds.
# PHP_MAX_INPUT_TIME=300

## Additional PHP Settings
# Timeout (in minutes) for user session inactivity.
# PHP_TIMEOUT=60
# Session cookie validity period in minutes.
# PHP_COOKIE_TIMEOUT=10080
# Default PHP configurations.
# PHP_DEFAULTS=php
# Automatically regenerate session ID on each request.
# PHP_AUTO_REGENERATE=false
# Check user agent on each request for security.
# PHP_CHECK_AGENT=false
# Only send session cookies over HTTPS.
# PHP_COOKIE_SECURE=true
# Domain for session cookie validity (leave empty for current domain).
# PHP_COOKIE_DOMAIN=
# SameSite policy for cookies ("Lax" allows top-level navigation).
# PHP_COOKIE_SAMESITE=Lax
```

2024-10-04 14:56 UTC, ostefano commented
Both work (personally like the second one as it is more concise).

Would it make sense to prefix some of the vars related to session management with `PHP_SESSION`?

2024-10-04 15:04 UTC, Diogo-Rego commented
> Both work (personally like the second one as it is more concise).
> 
> Would it make sense to prefix some of the vars related to session management with `PHP_SESSION`?

@ostefano 
For someone that knows how to use it, I don't think it makes sense but for others that are new to this variable type I believe that it does indeed make sense to have a base standard. MISP also puts these like this by default. What do you think ?

2024-10-04 15:39 UTC, Diogo-Rego commented
@ostefano confirm?

2024-10-04 15:40 UTC, ostefano commented
Sounds good! 👍

2024-10-06 08:42 UTC, ostefano commented on core/files/configure_misp.sh
> +set_up_proxy() {
I guess this is part of a future PR?

2024-10-06 08:42 UTC, ostefano commented on template.env
> +# Timeout (in minutes) for user session inactivity.
Please change variable names as discussed

2024-10-06 08:43 UTC, ostefano requested changes
See comments for changes requested

2024-10-06 12:41 UTC, Diogo-Rego commented
@ostefano can you confirm

2024-10-06 13:01 UTC, ostefano approved these changes

2024-10-09 14:21 UTC, ostefano commented
@Diogo-Rego tried the PR and first execution prints:

```
misp-core-1     | MISP | Set Up Session ...
misp-core-1     | Provided new config is not array, `NULL` given.
misp-core-1     | ... Session configured
```

Is that expected?

2024-10-09 14:22 UTC, ostefano reviewed
To investigate error message

2024-10-09 14:55 UTC, Diogo-Rego commented
> misp-core-1     | Provided new config is not array, `NULL` given.

I'll confirm the error

2024-10-09 15:54 UTC, Diogo-Rego commented
@ostefano confirm

2024-10-10 11:07 UTC, Diogo-Rego commented
@ostefano Can you confirm if it works?

2024-10-10 11:09 UTC, ostefano commented
@Diogo-Rego Didn't have spare cycles today yet. Will get to it as soon as I can.

2024-10-10 12:49 UTC, ostefano commented
Works, merging it.

2024-10-10 12:49 UTC, merged