Issue 188
MISP/misp-docker pull request #192
Opened 2024-12-02 14:03 UTC by capile

Replaces PR #189 

Adds a bit of documentation on how to enable a different ATTACHMENTS_DIR and what other folders need to be mounted instead of the /var/www/MISP/app/files.

Places the attachments folder outside of the files/ structure, that will remain basically the same as the distribution, with the exception of files/img/and files/terms/, folders that should be affected by a NFS filesystem.

During initialization, checks if the files/ folder was mounted before performing any tasks on it.

2024-12-02 15:30 UTC, ostefano requested changes

2024-12-02 15:30 UTC, ostefano commented on docker-compose.yml
> +      - "ATTACHMENTS_DIR=${ATTACHMENTS_DIR:-/var/www/MISP/app/files}"
defaults for env vars should be defined here, but inside the json file

2024-12-02 15:30 UTC, ostefano commented on template.env
> +ATTACHMENTS_DIR=/var/www/MISP/app/files
Default should be unset

2024-12-02 18:27 UTC, capile commented
changes committed, but as it is, unsetting the `ATTACHMENTS_DIR` after if was set does not revert it back to `/var/www/MISP/files` (should it?)

If it should, I suggest to add it to the `/entrypoint.sh`

2024-12-06 14:29 UTC, ostefano commented
This has been merged as a squash commit here https://github.com/MISP/misp-docker/commit/6599e572970a9fb20843b386d2a5f7f0af22a79e

Closing this.

2024-12-06 14:29 UTC, closed without merging