Allow Redis over TLS
MISP/misp-docker pull request #49
Opened 2024-04-19 21:37 UTC by christianmg99

### What does it do?
It fixes #47 by prepending `tcp://` only when not present in `$REDIS_FQDN` already.

2024-04-20 18:43 UTC, ostefano commented
@christianmg99  is tls://redis.example.com handled correctly by MISP itself? In other words, what about configure_misp.sh? Did you try building the image and looking at diagnostics?

2024-04-20 18:46 UTC, ostefano requested changes
See comment. We need to make sure that `tls://` prefixed strings are correctly managed by MISP itself.

2024-04-20 19:26 UTC, christianmg99 commented
By the time I found the replacement was in the entrypoint I had already read all Misp code regarding redis_host, and all I saw was mindful about the variable starting with tls:// such as in [zmq plugin](https://github.com/MISP/MISP/blob/471840ce33233a8d9db86766d007153f66727e8d/app/files/scripts/mispzmq/mispzmq.py#L91) and in [PHP-redis plugin](https://github.com/phpredis/phpredis/blob/62cf943fecc5182c6329b332df43cf28012cef55/README.md?plain=1#L241), I also looked into cakePHP and it has url prefix parsers as well. I currently use it like that in a custom deployment and it works fine.

2024-04-20 19:29 UTC, christianmg99 commented
Anyways, as it is coded, you would need to prepend tls:// anyways for it to be used, so it's only for the ones who want to "force" tls use in the variable like me that will take place, everyone else will follow the standard tcp:// prepend.

2024-04-20 19:29 UTC, ostefano commented on core/files/entrypoint_fpm.sh
> -        sed -i "s|.*session.save_path = .*|session.save_path = 'tcp://${REDIS_FQDN}:6379'|" "$FILE"
Why removing the space after `=`?

2024-04-20 19:32 UTC, christianmg99 commented on core/files/entrypoint_fpm.sh
> -        sed -i "s|.*session.save_path = .*|session.save_path = 'tcp://${REDIS_FQDN}:6379'|" "$FILE"
With the space there, if the space goes missing in the original file the replacement never takes place. It is more human readable with the space but facilitates some window for sed not catching on the string. Anyways if you want I can commit with the space back.

2024-04-20 19:35 UTC, christianmg99 commented on core/files/entrypoint_fpm.sh
> -        sed -i "s|.*session.save_path = .*|session.save_path = 'tcp://${REDIS_FQDN}:6379'|" "$FILE"
Or feel free to do so yourself, I believe I open the request allowing you to commit on top

2024-04-20 19:35 UTC, ostefano commented on core/files/entrypoint_fpm.sh
> -        sed -i "s|.*session.save_path = .*|session.save_path = 'tcp://${REDIS_FQDN}:6379'|" "$FILE"
I am not the original author of these `sed` commands, so I would rather leave them as such or change them all.

2024-04-20 19:56 UTC, christianmg99 commented on core/files/entrypoint_fpm.sh
> -        sed -i "s|.*session.save_path = .*|session.save_path = 'tcp://${REDIS_FQDN}:6379'|" "$FILE"
Space is back :)

2024-04-21 12:00 UTC, ostefano approved these changes

2024-04-22 08:20 UTC, merged